### ISSUE TITLE
Getting error when running on concolicexample.apk

### ISSUE THREAD

**Issue by ankitku** [JulianSchuette/ConDroid#5]
When running on concolicexample.apk, I get an error as shown below. What could be the cause?

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2045-04-25) or after any future revocation date.
[main] INFO acteve.instrumentor.Main - Done. Have fun with /Users/ankitku/dev/ConDroid/sootOutput/concolicexample_modified.apk
[main] DEBUG acteve.explorer.Config - useMonkeyScript=false
[main] DEBUG acteve.explorer.Config - monkey=monkey_script.txt
[main] DEBUG acteve.explorer.Config - pkg=null
[main] DEBUG acteve.explorer.Config - mainact=null
[main] DEBUG acteve.explorer.Config - actargs=
[main] DEBUG acteve.explorer.Config - max.iters=1000
[main] DEBUG acteve.explorer.Config - out.dir=./results/
[main] DEBUG acteve.explorer.Config - port=5554
[main] DEBUG acteve.explorer.Config - userwait=4
[main] DEBUG acteve.explorer.Config - K=2
[main] DEBUG acteve.explorer.Config - indep=false
[main] DEBUG acteve.explorer.Config - readonly=false
[main] DEBUG acteve.explorer.Config - condmap.file=./out/condmap.txt
[main] DEBUG acteve.explorer.Config - fieldsigs.file=./out/fieldsigs.txt
[main] DEBUG acteve.explorer.Config - blackfields.file=null
[main] DEBUG acteve.explorer.Config - restart=false
[main] DEBUG acteve.explorer.Config - prune.last=false
[main] DEBUG acteve.explorer.Config - diverge.threshold=3
[main] DEBUG acteve.explorer.Config - wildemus.threshold=6
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results/adbout.5554
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results/pkg.txt
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results/script.txt
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results/script.txt.emu5554
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/./results/settings.txt.emu5554
[main] DEBUG acteve.explorer.Utils - Deleting /Users/ankitku/dev/ConDroid/results
[main] DEBUG acteve.explorer.ConcolicExecutor - using emulator running on port 5554
Setting up Z3 with /opt/z3/bin/z3
[main] DEBUG acteve.explorer.ConcolicPathsExplorer - Vanilla symex with currentRoundRunIds []
[main] DEBUG acteve.explorer.Path - Generating new script
[main] DEBUG acteve.explorer.Path - 	Smt file        : false - /Users/ankitku/dev/ConDroid/./results/pc.0.smt2 
[main] DEBUG acteve.explorer.Path - 	pc file         : false - /Users/ankitku/dev/ConDroid/pc.-1 
[main] DEBUG acteve.explorer.Path - 	pcDecl file     : false - /Users/ankitku/dev/ConDroid/./results/pc.-1.decl 
[main] DEBUG acteve.explorer.Path - 	scriptToRun file: false - /Users/ankitku/dev/ConDroid/./results/script.txt.0 
[main] DEBUG acteve.explorer.Path - 	Depth: 0
[main] DEBUG acteve.explorer.Path - 	id: 0
[main] DEBUG acteve.explorer.Path - 	seedId: -1
[main] DEBUG acteve.explorer.Path - No smt file exists, nothing to solve
[Worker-0] INFO acteve.explorer.ConcolicExecutor - 

Starting new path ID 0
[Worker-0] DEBUG acteve.explorer.ConcolicExecutor - Executing path 0 on emulator-5554
[Worker-0] DEBUG acteve.explorer.Emulator - Pushing /Users/ankitku/dev/ConDroid/./results/z3out.0 to /sdcard/solution.txt
[Worker-0] DEBUG acteve.explorer.Emulator - Starting logcat
[Worker-0] ERROR acteve.explorer.ConcolicExecutor - Error occurred while executing 0 on emulator-5554
null returned: 1
	at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:650)
	at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:676)
	at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:502)
	at acteve.explorer.AdbTask.execute(AdbTask.java:67)
	at acteve.explorer.Emulator.execute(Emulator.java:260)
	at acteve.explorer.Emulator.execute(Emulator.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:390)
	at acteve.explorer.Emulator.exec(Emulator.java:222)
	at acteve.explorer.ConcolicExecutor$Worker.executePath(ConcolicExecutor.java:228)
	at acteve.explorer.ConcolicExecutor$Worker.run(ConcolicExecutor.java:183)
Exception in thread "Worker-0" java.lang.Error: java.io.FileNotFoundException: ./results/syslog.0 (No such file or directory)
	at acteve.explorer.Path.checkForSWB(Path.java:437)
	at acteve.explorer.Path.postProcess(Path.java:251)
	at acteve.explorer.ConcolicExecutor$Worker.executePath(ConcolicExecutor.java:238)
	at acteve.explorer.ConcolicExecutor$Worker.run(ConcolicExecutor.java:183)
Caused by: java.io.FileNotFoundException: ./results/syslog.0 (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at acteve.explorer.Main.newReader(Main.java:142)
	at acteve.explorer.Path.checkForSWB(Path.java:424)
	... 3 more

**Comment by yufeiyang1995** [comment]
I met the same error. 
Have you ever resolved it?
@ankitku

**Comment by ankitku** [comment]
No, also I am unable to build ConDroid in eclipse.

**Comment by yufeiyang1995** [comment]
Well,I solved this error .
The file system of the device maybe is Read-only.
You can use the command 'mount -o remount -o rw /' in adb shell.
